[package]
name = "hello-genmini-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
base64 = "0.22.1"
reqwest = { version = "0.12.12", features = ["json"] }
serde_json =  "1"
tokio = { version = "1.43.0", features = ["full"] }
